"""Project-wide methodology and data settings."""

from pathlib import Path

DATA_START_DATE = "2005-01-01"
RAW_DATA_DIR = Path("data") / "raw"

DEFAULT_DOWNLOAD_TIMEOUT_SECONDS = 30
DEFAULT_DOWNLOAD_RETRIES = 3
DEFAULT_RETRY_BACKOFF_SECONDS = 1.0

DEFAULT_GPR_SHOCK_QUANTILE = 0.90
GPR_EXPANDING_SHOCK_MIN_PERIODS = 252

LARGE_RETURN_THRESHOLD = 0.20

EVENT_MIN_GAP_DAYS = 20
EVENT_WINDOW_DAYS = 5
EVENT_ESTIMATION_WINDOW_DAYS = 120
EVENT_ESTIMATION_GAP_DAYS = 20
EVENT_MIN_ESTIMATION_OBS = 80
EVENT_ROBUSTNESS_SHOCK_QUANTILES = [0.90, 0.95]
EVENT_ROBUSTNESS_WINDOWS = [3, 5, 10]
EVIDENCE_EVENT_SHOCK_QUANTILE = 0.90
EVIDENCE_EVENT_WINDOW_DAYS = 10

LOCAL_PROJECTION_MAX_HORIZON = 20

QUANTILE_REGRESSION_QUANTILES = [0.10, 0.25, 0.50]

ROLLING_BETA_WINDOW_DAYS = 252
ROLLING_BETA_MIN_PERIODS = 126

DRAWDOWN_HORIZON_DAYS = 20
DRAWDOWN_THRESHOLD = -0.05
DRAWDOWN_VOLATILITY_WINDOW_DAYS = 20
DRAWDOWN_N_SPLITS = 5

MARKET_CONTROL_TICKERS = {
    "ACWI": "global equity ETF",
    "^VIX": "VIX risk-aversion index",
    "CL=F": "WTI crude oil futures",
    "UUP": "US dollar ETF",
    "^TNX": "US 10-year Treasury yield index",
}
