UPDATE events SET catalyst_dates='[]';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-PZFFL0TDP3';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-99JZRM47M6';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-KWX3HB7XG9';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-V37TZKN222';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-X1SJDG9QQ8';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-H50NT0MZ04';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-L7017DJDX1';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-5P6C5JFKT9';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-RBY62SKLC0';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-VB6B4LJ482';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-7W5ZNTWXW6';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-X2TT2M9D02';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-LMCP7ZD299';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-7DJ55H2YG5';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-F6046BB5W1';
UPDATE events SET catalyst_types='["cpi", "fomc", "earnings:AAPL", "earnings:MSFT", "earnings:GOOGL", "earnings:AMZN", "earnings:NVDA", "earnings:META", "earnings:TSLA"]' WHERE event_id='CM-EVT-P3C38JNNT7';
UPDATE events SET catalyst_types='["cpi", "fomc", "earnings:AAPL", "earnings:MSFT", "earnings:GOOGL", "earnings:AMZN", "earnings:NVDA", "earnings:META", "earnings:TSLA"]' WHERE event_id='CM-EVT-0RZ3HRXJN8';
UPDATE events SET catalyst_types='["cpi", "fomc", "earnings:AAPL", "earnings:MSFT", "earnings:GOOGL", "earnings:AMZN", "earnings:NVDA", "earnings:META", "earnings:TSLA"]' WHERE event_id='CM-EVT-19C8FVK4P0';
UPDATE events SET catalyst_types='["cpi", "fomc", "earnings:AAPL", "earnings:MSFT", "earnings:GOOGL", "earnings:AMZN", "earnings:NVDA", "earnings:META", "earnings:TSLA"]' WHERE event_id='CM-EVT-DTKS54W7T6';
UPDATE events SET catalyst_types='["cpi", "fomc", "earnings:AAPL", "earnings:MSFT", "earnings:GOOGL", "earnings:AMZN", "earnings:NVDA", "earnings:META", "earnings:TSLA"]' WHERE event_id='CM-EVT-FK9S1HQHB6';
UPDATE events SET catalyst_types='["cpi", "fomc", "earnings:AAPL", "earnings:MSFT", "earnings:GOOGL", "earnings:AMZN", "earnings:NVDA", "earnings:META", "earnings:TSLA"]' WHERE event_id='CM-EVT-JPWZDPJ339';
UPDATE events SET catalyst_types='["cpi", "fomc", "earnings:AAPL", "earnings:MSFT", "earnings:GOOGL", "earnings:AMZN", "earnings:NVDA", "earnings:META", "earnings:TSLA"]' WHERE event_id='CM-EVT-HD4HXWSDD9';
UPDATE events SET catalyst_types='["cpi", "fomc", "earnings:AAPL", "earnings:MSFT", "earnings:GOOGL", "earnings:AMZN", "earnings:NVDA", "earnings:META", "earnings:TSLA"]' WHERE event_id='CM-EVT-HYFSJ2CNW7';
UPDATE events SET catalyst_types='["cpi", "fomc", "earnings:AAPL", "earnings:MSFT", "earnings:GOOGL", "earnings:AMZN", "earnings:NVDA", "earnings:META", "earnings:TSLA"]' WHERE event_id='CM-EVT-K47V5LVKY9';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-284V3KPHS0';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-7SBTK0NC26';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-1XDQZN2B72';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-4D6X8P7422';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-K0L95NMQ77';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-T57DHL6V48';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-MR57HVWJT3';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-6CSLHX0K76';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-6BS28TS762';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-F9NPW9F1V9';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-18Z2VTMCX0';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-4ZQLQPNH91';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-D057W6W251';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-7F62GCV784';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-2HHFZDLC17';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-XP5XZNK7W3';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-YFTJTYGW53';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-W0RC4VCRZ5';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-HVKDYMRT39';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-TTR8WH64R6';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-BHTHYWRLH7';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-PHWX2H6DM5';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-46SP3GT7N4';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-KRRTGX1QB3';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-DKLJV3BYH6';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-FC6YNQPJV4';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-B5KCGZG8C0';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-KJ2LGV0M57';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-85LZKDJL71';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-X69Q9MZJJ5';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-MZGHWX20T0';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-RJ6SMJGK50';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-112L9VRK74';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-LZG1M8W7R7';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-D2SCD1PLP2';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-LRHXKJ8DC8';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-680PYKKLZ6';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-1RDJLJZL71';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-5F0G9L6HV6';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-S299B265X5';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-CF4GQ5PDX0';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-5HWQGSV711';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-GX15VWGX92';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-JVSPDQ1P92';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-W5JLW7Z0S4';
UPDATE events SET catalyst_types='["cpi", "fomc", "earnings:AAPL", "earnings:MSFT", "earnings:GOOGL", "earnings:AMZN", "earnings:NVDA", "earnings:META", "earnings:TSLA"]' WHERE event_id='CM-EVT-016Z206N61';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-8FTQ6W5354';
UPDATE events SET catalyst_types='["cpi", "fomc", "earnings:AAPL", "earnings:MSFT", "earnings:GOOGL", "earnings:AMZN", "earnings:NVDA", "earnings:META", "earnings:TSLA"]' WHERE event_id='CM-EVT-8W89HNJVQ1';
UPDATE events SET catalyst_types='["cpi", "fomc", "earnings:AAPL", "earnings:MSFT", "earnings:GOOGL", "earnings:AMZN", "earnings:NVDA", "earnings:META", "earnings:TSLA"]' WHERE event_id='CM-EVT-HMJ9TY5QY9';
UPDATE events SET catalyst_types='["cpi", "fomc", "earnings:AAPL", "earnings:MSFT", "earnings:GOOGL", "earnings:AMZN", "earnings:NVDA", "earnings:META", "earnings:TSLA"]' WHERE event_id='CM-EVT-03M3NDMR10';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-FGMH0SRW94';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-943Z5Y3NP4';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-0TSMZBY6R6';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-4F238D6VR7';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-BD6QB5GC44';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-NN523F6SZ3';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-RLQQ3VJDS6';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-YNPRYST5T1';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-87QV1G78C4';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-6WY59L0G19';
UPDATE events SET catalyst_types='["cpi", "fomc", "earnings:AAPL", "earnings:MSFT", "earnings:GOOGL", "earnings:AMZN", "earnings:NVDA", "earnings:META", "earnings:TSLA"]' WHERE event_id='CM-EVT-3HDQG11JV0';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-D02KL9HMC3';
UPDATE events SET catalyst_types='["cpi", "fomc", "earnings:AAPL", "earnings:MSFT", "earnings:GOOGL", "earnings:AMZN", "earnings:NVDA", "earnings:META", "earnings:TSLA"]' WHERE event_id='CM-EVT-DC7V7Y6TN3';
UPDATE events SET catalyst_types='["cpi", "fomc", "earnings:AAPL", "earnings:MSFT", "earnings:GOOGL", "earnings:AMZN", "earnings:NVDA", "earnings:META", "earnings:TSLA"]' WHERE event_id='CM-EVT-B3PGCW67Y8';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-YCJGDPJL85';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-WB85BV4T72';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-PWVBZ3JY79';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-R6DPP799Q0';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-LFH7SZTVZ8';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-CJQJ8SK6S4';
UPDATE events SET catalyst_types='["cpi", "fomc", "earnings:AAPL", "earnings:MSFT", "earnings:GOOGL", "earnings:AMZN", "earnings:NVDA", "earnings:META", "earnings:TSLA"]' WHERE event_id='CM-EVT-3GLLKKKMD5';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-GP3DJ4Z2P3';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-T0Z4DKV587';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-HH2P3WVFN2';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-1QS9WGDYF1';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-GYH2GBCZK2';
UPDATE events SET catalyst_types='["cpi", "jobs", "gdp", "fomc"]' WHERE event_id='CM-EVT-LZ9Q8BDFL0';
UPDATE events SET catalyst_types='["cpi", "fomc", "earnings:AAPL", "earnings:MSFT", "earnings:GOOGL", "earnings:AMZN", "earnings:NVDA", "earnings:META", "earnings:TSLA"]' WHERE event_id='CM-EVT-2M1WYBFS49';
UPDATE events SET catalyst_types='["cpi", "fomc", "earnings:AAPL", "earnings:MSFT", "earnings:GOOGL", "earnings:AMZN", "earnings:NVDA", "earnings:META", "earnings:TSLA"]' WHERE event_id='CM-EVT-DXV83328C1';
UPDATE events SET catalyst_types='["cpi", "fomc", "earnings:AAPL", "earnings:MSFT", "earnings:GOOGL", "earnings:AMZN", "earnings:NVDA", "earnings:META", "earnings:TSLA"]' WHERE event_id='CM-EVT-B4ZXHGVWY3';
DROP TABLE IF EXISTS catalyst_calendar;
CREATE TABLE catalyst_calendar (type TEXT PRIMARY KEY, label TEXT NOT NULL, source_url TEXT NOT NULL, dates TEXT NOT NULL);
INSERT INTO catalyst_calendar (type,label,source_url,dates) VALUES ('cpi','CPI release','https://www.bls.gov/cpi/','["2026-06-10", "2026-07-14", "2026-08-12", "2026-09-11", "2026-10-14", "2026-11-10", "2026-12-10"]');
INSERT INTO catalyst_calendar (type,label,source_url,dates) VALUES ('jobs','Employment Situation','https://www.bls.gov/ces/','["2026-06-05", "2026-07-02", "2026-08-07", "2026-09-04", "2026-10-02", "2026-11-06", "2026-12-04"]');
INSERT INTO catalyst_calendar (type,label,source_url,dates) VALUES ('gdp','GDP release','https://www.bea.gov/data/gdp/gross-domestic-product','["2026-06-25", "2026-07-30", "2026-08-26", "2026-09-30", "2026-10-29", "2026-11-25", "2026-12-23"]');
INSERT INTO catalyst_calendar (type,label,source_url,dates) VALUES ('fomc','FOMC rate decision','https://www.federalreserve.gov/monetarypolicy/fomccalendars.htm','["2026-06-17", "2026-07-29", "2026-09-16", "2026-10-28", "2026-12-09"]');
INSERT INTO catalyst_calendar (type,label,source_url,dates) VALUES ('earnings:AAPL','AAPL earnings','https://finnhub.io/quote/AAPL','["2026-07-29"]');
INSERT INTO catalyst_calendar (type,label,source_url,dates) VALUES ('earnings:MSFT','MSFT earnings','https://finnhub.io/quote/MSFT','["2026-07-28"]');
INSERT INTO catalyst_calendar (type,label,source_url,dates) VALUES ('earnings:GOOGL','GOOGL earnings','https://finnhub.io/quote/GOOGL','["2026-07-21"]');
INSERT INTO catalyst_calendar (type,label,source_url,dates) VALUES ('earnings:AMZN','AMZN earnings','https://finnhub.io/quote/AMZN','["2026-07-29"]');
INSERT INTO catalyst_calendar (type,label,source_url,dates) VALUES ('earnings:NVDA','NVDA earnings','https://finnhub.io/quote/NVDA','["2026-08-25"]');
INSERT INTO catalyst_calendar (type,label,source_url,dates) VALUES ('earnings:META','META earnings','https://finnhub.io/quote/META','["2026-07-28"]');
INSERT INTO catalyst_calendar (type,label,source_url,dates) VALUES ('earnings:TSLA','TSLA earnings','https://finnhub.io/quote/TSLA','["2026-07-21"]');
INSERT INTO catalyst_calendar (type,label,source_url,dates) VALUES ('earnings:UBER','UBER earnings','https://finnhub.io/quote/UBER','["2026-08-04"]');
INSERT INTO catalyst_calendar (type,label,source_url,dates) VALUES ('earnings:MELI','MELI earnings','https://finnhub.io/quote/MELI','["2026-08-05"]');
INSERT INTO catalyst_calendar (type,label,source_url,dates) VALUES ('earnings:SNOW','SNOW earnings','https://finnhub.io/quote/SNOW','["2026-08-25"]');
INSERT INTO catalyst_calendar (type,label,source_url,dates) VALUES ('earnings:DELL','DELL earnings','https://finnhub.io/quote/DELL','["2026-05-28"]');
INSERT INTO catalyst_calendar (type,label,source_url,dates) VALUES ('earnings:AVGO','AVGO earnings','https://finnhub.io/quote/AVGO','["2026-06-03"]');
INSERT INTO catalyst_calendar (type,label,source_url,dates) VALUES ('earnings:MU','MU earnings','https://finnhub.io/quote/MU','["2026-06-23"]');
INSERT INTO catalyst_calendar (type,label,source_url,dates) VALUES ('earnings:MTN','MTN earnings','https://finnhub.io/quote/MTN','["2026-06-08"]');
INSERT INTO catalyst_calendar (type,label,source_url,dates) VALUES ('earnings:HOOD','HOOD earnings','https://finnhub.io/quote/HOOD','["2026-07-28"]');
INSERT INTO catalyst_calendar (type,label,source_url,dates) VALUES ('earnings:FUTU','FUTU earnings','https://finnhub.io/quote/FUTU','["2026-05-28", "2026-08-18"]');
