UPDATE events SET question='Will United Airlines Holdings Inc. report Above 180 million passengers flown in 2026?' WHERE event_id='CM-EVT-XL3H4QDNB2';
UPDATE events SET question='Will Starbucks Corporation report Above 41500 total global stores in 2026?' WHERE event_id='CM-EVT-KLZTSTHRW4';
UPDATE events SET question='Who will run for the Democratic presidential nomination in 2028?' WHERE event_id='CM-EVT-5H09B63413';
UPDATE events SET question='Will the margin of victory for Ken Paxton in the U.S. Senate primary election in Texas be at least 12 percentage points?' WHERE event_id='CM-EVT-XS8332JBB4';
UPDATE events SET question='Will the margin of victory for Democrats in the Oregon''s 3rd District House election be at least 38 percentage points?' WHERE event_id='CM-EVT-98TTCLWRD8';
UPDATE events SET question='Will the margin of victory for Democrats in the Ohio''s 13th District House election be at least 2 percentage points?' WHERE event_id='CM-EVT-RL4DPXZ231';
UPDATE events SET question='Will the margin of victory for Democrats in the New Hampshire''s 2nd District House election be at least 4 percentage points?' WHERE event_id='CM-EVT-PQ0MKZ50Q6';
UPDATE events SET question='Will the margin of victory for Democrats in the Minnesota''s 2nd District House election be at least 13 percentage points?' WHERE event_id='CM-EVT-3YTF9WJQ37';
UPDATE events SET question='Will the margin of victory for Democrats in the Kansas''s 3rd District House election be at least 14 percentage points?' WHERE event_id='CM-EVT-V0LHDFSSG6';
UPDATE events SET question='Will the margin of victory for Republicans in the Indiana''s 5th District House election be at least 1 percentage points?' WHERE event_id='CM-EVT-S26P9Y15Q9';
UPDATE events SET question='Will the margin of victory for Democrats in the Connecticut''s 1st District House election be at least 22 percentage points?' WHERE event_id='CM-EVT-92PYSZMSS2';
UPDATE events SET question='Will the margin of victory for Republicans in the Arkansas''s 3rd District House election be at least 19 percentage points?' WHERE event_id='CM-EVT-BL6HFHK4H3';
UPDATE events SET question='Will the margin of victory for Graham Platner in the 2026 Maine Democratic Senate primary be above 50%?' WHERE event_id='CM-EVT-09QF876RS2';
UPDATE events SET question='Will the margin of victory for Keiko Fujimori in the 2026 Peru presidential election runoff be between 0% and 3%?' WHERE event_id='CM-EVT-RKB4074MH9';
UPDATE events SET question='Will Steve Hilton receive at least 24% of the popular vote in the 2026 California gubernatorial primary?' WHERE event_id='CM-EVT-WS60V9CW99';
UPDATE events SET question='Will Zach Lahn receive between 35% and 40% of the popular vote in the 2026 Iowa Republican gubernatorial primary?' WHERE event_id='CM-EVT-WLD8CTHJF5';
UPDATE events SET question='Will the margin of victory for Ken Paxton in the 2026 Texas Republican Senate runoff be between 20% and 100%?' WHERE event_id='CM-EVT-WDW9695BR8';
UPDATE events SET question='Will Ed Diehl receive between 30% and 35% of the popular vote in the 2026 Oregon Republican gubernatorial primary?' WHERE event_id='CM-EVT-B8M2V9V998';
UPDATE events SET question='Will the margin of victory for Karen Bass in the first round of the 2026 Los Angeles mayoral election be between 4% and 8%?' WHERE event_id='CM-EVT-D63V66YZ42';
UPDATE events SET question='Will the number of Trump rallies be above 15 from January 1 to November 3, 2026?' WHERE event_id='CM-EVT-8CL5HBK172';
UPDATE events SET question='State of the economy at the end of 2026?' WHERE event_id='CM-EVT-ZRG5DFDMZ8';
UPDATE events SET question='Above 0 New World screwworm infestation cases in the United States during 2026' WHERE event_id='CM-EVT-ZX2HKB77S0';
UPDATE events SET question='Will Donald Trump meet in person Xi Jinping before Jan 1, 2027?' WHERE event_id='CM-EVT-WY1J5J92Q7';
UPDATE events SET question='Will Dem Nominee be Graham Platner AND General Election Winner be Democrat for Jan 2027?' WHERE event_id='CM-EVT-2KYR51YTD3';
UPDATE events SET question='Will the United States have at least 4,400 data centers listed in 2026?' WHERE event_id='CM-EVT-8X6YW3Q5T3';
UPDATE events SET question='ETH price  on Jan 1, 2027?' WHERE event_id='CM-EVT-M6M011NKR6';
UPDATE events SET question='BTC price  on Jan 1, 2027?' WHERE event_id='CM-EVT-0WKFGLC4Y3';
UPDATE events SET question='Will Bitcoin be above $99,999.99 by Dec 31, 2026 at 11:59 PM ET?' WHERE event_id='CM-EVT-0MWN62PNG9';
UPDATE events SET question='Will the Nasdaq-100 be above 26000 on Dec 31, 2026 at 4pm EST?' WHERE event_id='CM-EVT-GNKG1GYDT6';
UPDATE events SET question='Will the Nasdaq-100 be below 19000 at the end of Dec 31, 2026 at 4pm EST?' WHERE event_id='CM-EVT-JPWZDPJ339';
UPDATE events SET question='Will the S&P 500 be between 7600 and 7799.99 on Dec 31, 2026 at 4pm EST?' WHERE event_id='CM-EVT-K47V5LVKY9';
UPDATE events SET question='Who will win the governorship in Alaska?' WHERE event_id='CM-EVT-B206SG3QQ3';
UPDATE events SET question='Will there be more than 14  Atlantic hurricanes in 2026?' WHERE event_id='CM-EVT-Q08SZJTP95';
UPDATE events SET question='Will John E. Sununu be the Republican nominee for the Senate in New Hampshire?' WHERE event_id='CM-EVT-TJYWW9Y1N3';
UPDATE events SET question='Will Mike Collins be the Republican nominee for the Senate in Georgia?' WHERE event_id='CM-EVT-T993NRVBH0';
UPDATE events SET question='Will DoorDash Inc. report above 960 million total orders in Q2 2026?' WHERE event_id='CM-EVT-GKGRRKSX88';
UPDATE events SET question='Will Boeing Company (The) report Above 160 commercial deliveries in Q2 2026?' WHERE event_id='CM-EVT-2LPBXMC1G4';
UPDATE events SET question='Will Tesla Inc. report above 450000 total deliveries in Q2 2026?' WHERE event_id='CM-EVT-40YSQ5G480';
UPDATE events SET question='Will Elon Musk''s net worth for June be above $790 billion?' WHERE event_id='CM-EVT-60SJ29HKD1';
UPDATE events SET question='Will UST Par Yield Curve (30Y) for Q2 2026 be above 4.00%?' WHERE event_id='CM-EVT-W8J78TQV54';
UPDATE events SET question='Donald Trump and Mohammed bin Salman meet before Jul 1, 2026?' WHERE event_id='CM-EVT-ZD3ST0T7T1';
UPDATE events SET question='Will there be more than 200 tornadoes in June?' WHERE event_id='CM-EVT-Y0JJ5168N1';
UPDATE events SET question='Will the tariff rate on China imports be between 10% and 19.99% on Jul 1, 2026?' WHERE event_id='CM-EVT-0F3FPFL7B8';
UPDATE events SET question='Will the maximum temperature be >81° on Jun 12, 2026?' WHERE event_id='CM-EVT-99BZM0NWZ4';
UPDATE events SET question='Will the **high temp in LA** be 76-77° on Jun 12, 2026?' WHERE event_id='CM-EVT-BFYBC2WCQ5';
UPDATE events SET question='Will the Nasdaq-100 be above 29599.99 at the end of Jun 12, 2026 at 4pm EDT?' WHERE event_id='CM-EVT-7WM4HP0RK3';
UPDATE events SET question='Will the S&P 500 be above 7399.9999 on Jun 12, 2026 at 4pm EDT?' WHERE event_id='CM-EVT-V0ZM4S0VY8';
UPDATE events SET question='Ripple price at Jun 12, 2026 at 5pm EDT?' WHERE event_id='CM-EVT-SRQ6K7X805';
UPDATE events SET question='SOL price on Jun 12, 2026?' WHERE event_id='CM-EVT-RJPHNCK7Y9';
UPDATE events SET question='Ethereum price at Jun 12, 2026 at 5pm EDT?' WHERE event_id='CM-EVT-DHX6PKKLB4';
UPDATE events SET question='Bitcoin price on Jun 12, 2026?' WHERE event_id='CM-EVT-K33LB9Q822';
UPDATE events SET question='Bitcoin price on Jun 12, 2026?' WHERE event_id='CM-EVT-XSZ69TB080';
UPDATE events SET question='Will the Nasdaq-100 be above 29589.99 at the end of Jun 12, 2026 at 2pm EDT?' WHERE event_id='CM-EVT-F0YZ13BY50';
UPDATE events SET question='Will the S&P 500 be above 7419.9999 on Jun 12, 2026 at 2pm EDT?' WHERE event_id='CM-EVT-VVZRBYFJ14';
UPDATE events SET question='Will Xavier Becerra receive between 28% and 32% of the popular vote in the 2026 California gubernatorial primary?' WHERE event_id='CM-EVT-J3BXGY3MS6';
UPDATE events SET question='Will Steve Hilton receive between 24% and 28% of the popular vote in the 2026 California gubernatorial primary?' WHERE event_id='CM-EVT-82FXFQ2GW9';
UPDATE events SET question='Will the Republicans win the Idaho Senate race in 2026?' WHERE event_id='CM-EVT-HW8FT0L534';
UPDATE events SET question='Will Trump meet with Xi Jinping in 2026?' WHERE event_id='CM-EVT-D2FSS8S8N5';
UPDATE events SET question='Will NVIDIA be the largest company in the world by market cap on December 31?' WHERE event_id='CM-EVT-WMBW6M11T5';
UPDATE events SET question='Will Paramount close Warner Bros acquisition?' WHERE event_id='CM-EVT-CP17BTS9G2';
UPDATE events SET question='Will USD/KRW hit 1500 (High) in 2026?' WHERE event_id='CM-EVT-PJB0JX5488';
UPDATE events SET question='Will USD/CAD hit 1.45 (High) in 2026?' WHERE event_id='CM-EVT-K34H6Z9YH8';
UPDATE events SET question='Will the sender of the “I beat Bush” email to Epstein not be revealed in 2026?' WHERE event_id='CM-EVT-C4JY7HLGG8';
UPDATE events SET question='Will Matthieu Pigasse be on the ballot for the 2027 French presidential election?' WHERE event_id='CM-EVT-6Q8LZ5QQW0';
UPDATE events SET question='Over $250k committed to the ALIGN public sale?' WHERE event_id='CM-EVT-3LDXH90Y48';
UPDATE events SET question='Will Keir Starmer be a candidate in the next Labour Party leadership election?' WHERE event_id='CM-EVT-5PQ4Z7D292';
UPDATE events SET question='Will Apple be the second-largest company in the world by market cap on June 30?' WHERE event_id='CM-EVT-5MSNF28G94';
UPDATE events SET question='Will Anthropic''s valuation hit (HIGH) $2.0T by December 31?' WHERE event_id='CM-EVT-7Y9Q6XSHM9';
UPDATE events SET question='Will OpenAI have the highest private market valuation on June 30?' WHERE event_id='CM-EVT-Z4Y6TF2QS5';
UPDATE events SET question='Will Micron Q3 NAND revenue be above $8.0B?' WHERE event_id='CM-EVT-L1ZYNSRRT3';
UPDATE events SET question='Will Elon Musk post 0-19 tweets in July 2026?' WHERE event_id='CM-EVT-5HV3KF4YB2';
UPDATE events SET question='Will Alphabet Inc. (GOOGL) hit (HIGH) $400 in June?' WHERE event_id='CM-EVT-5D744ZJK94';
UPDATE events SET question='Will Elon Musk’s net worth be at least $800b on June 30?' WHERE event_id='CM-EVT-GGSHQGLR04';
UPDATE events SET question='Will Trump speak to Ahmed al-Sharaa in June?' WHERE event_id='CM-EVT-33HY7CLT67';
UPDATE events SET question='Will Bank of America (BAC) Q2 provision for credit losses be above $1.3B?' WHERE event_id='CM-EVT-9YVW9JCCR1';
UPDATE events SET question='Will there be between 0 and 10 average daily transits of the Strait of Hormuz on June 30?' WHERE event_id='CM-EVT-WVPPDSXFX0';
UPDATE events SET question='Will 100 or more ships transit the Strait of Hormuz between June 8-June 14?' WHERE event_id='CM-EVT-6S1MBX3KJ4';
UPDATE events SET question='Will WTI Crude Oil (WTI) hit (LOW) $85 Week of June 8 2026?' WHERE event_id='CM-EVT-N03YMHZQS2';
UPDATE events SET question='Will Elon Musk post 80-99 tweets from June 9 to June 16, 2026?' WHERE event_id='CM-EVT-8G1WQ42GN2';
UPDATE events SET question='Will the price of Bitcoin be between $60,000 and $62,000 on June 13?' WHERE event_id='CM-EVT-LC9ZH6NY20';
UPDATE events SET question='Will the price of Ethereum be above $1,400 on June 14?' WHERE event_id='CM-EVT-3SW5YVHZZ9';
UPDATE events SET question='Will the price of Bitcoin be between $58,000 and $60,000 on June 14?' WHERE event_id='CM-EVT-8RJZY8SZV4';
UPDATE events SET question='Will the price of Ethereum be between $1,500 and $1,600 on June 14?' WHERE event_id='CM-EVT-VCSGH0CXM8';
UPDATE events SET question='Will the price of Bitcoin be between $60,000 and $62,000 on June 15?' WHERE event_id='CM-EVT-Y53ZR06P96';
UPDATE events SET question='Will Donald Trump attend the G7 Summit?' WHERE event_id='CM-EVT-D90PT3YL41';
UPDATE events SET question='Will Elon Musk post 500+ tweets from June 12 to June 19, 2026?' WHERE event_id='CM-EVT-9RP547RD48';
UPDATE events SET question='Will Eugene Vindman be the Democratic nominee for VA-07?' WHERE event_id='CM-EVT-B03BDVL0F2';
UPDATE events SET question='Will Beth Macy be the Democratic nominee for VA-06?' WHERE event_id='CM-EVT-Y3QGZNMZ41';
UPDATE events SET question='Will Bobby Scott be the Democratic nominee for VA-03?' WHERE event_id='CM-EVT-41N2708XK7';
UPDATE events SET question='Will Ronald Russell be the Republican nominee for ME-01?' WHERE event_id='CM-EVT-V5NVLCSQ79';
UPDATE events SET question='Will Pete Aguilar advance in the 2026 CA-33 primary?' WHERE event_id='CM-EVT-4NKG9TSSN7';
UPDATE events SET question='Will Jim Costa advance in the 2026 CA-21 primary?' WHERE event_id='CM-EVT-73CJSS2RS4';
UPDATE events SET question='Will Zoe Lofgren advance in the 2026 CA-18 primary?' WHERE event_id='CM-EVT-G1GTLZ05L5';
UPDATE events SET question='Will Kevin Mullin advance in the 2026 CA-15 primary?' WHERE event_id='CM-EVT-W7060501S0';
UPDATE events SET question='Will Lindsey Graham be the Republican nominee for the Senate in South Carolina?' WHERE event_id='CM-EVT-DH1BN6B9Q5';
UPDATE events SET question='Will Ryan Busse be the Democratic nominee for MT-01?' WHERE event_id='CM-EVT-VDRPQ34M22';
UPDATE events SET question='Will the UK designate the IRGC a terrorist organization by June 30?' WHERE event_id='CM-EVT-5SN6B7W5V0';
UPDATE events SET question='Will Christy Davis be the Democratic nominee for Senate in Kansas?' WHERE event_id='CM-EVT-G6QSZJ9ZC2';
UPDATE events SET question='Will the Republican Party win the OH-09 House seat?' WHERE event_id='CM-EVT-F4DM8HPC69';
UPDATE events SET question='Will Paul LePage be the Republican Nominee for ME-02?' WHERE event_id='CM-EVT-QP3JWHYZN3';
UPDATE events SET question='Will the Republican Party win the AL-03 House seat?' WHERE event_id='CM-EVT-D0MKFGTPL9';
UPDATE events SET question='Will the Democratic Party win the CA-15 House seat?' WHERE event_id='CM-EVT-P8GPV0BPK8';
UPDATE events SET question='Will the Democratic Party win the CA-16 House seat?' WHERE event_id='CM-EVT-VXZ6211B15';
UPDATE events SET question='Will the Democratic Party win the CA-19 House seat?' WHERE event_id='CM-EVT-S1JW5708M7';
UPDATE events SET question='Will the Democratic Party win the CA-29 House seat?' WHERE event_id='CM-EVT-LZ6CGDTS66';
UPDATE events SET question='Will the Republican Party win the CA-46 House seat?' WHERE event_id='CM-EVT-Q44D460T30';
UPDATE events SET question='Will the Republican Party win the FL-14 House seat?' WHERE event_id='CM-EVT-LPBNKVP3F9';
UPDATE events SET question='Will the Republican Party win the FL-20 House seat?' WHERE event_id='CM-EVT-CZLJ90HJX3';
UPDATE events SET question='Will the Republican Party win the FL-22 House seat?' WHERE event_id='CM-EVT-3LYCR5RYW8';
UPDATE events SET question='Will the Republican Party win the FL-25 House seat?' WHERE event_id='CM-EVT-HQP7KZ8L31';
UPDATE events SET question='Will the Republican Party win the IN-05 House seat?' WHERE event_id='CM-EVT-2Y2596TYD9';
UPDATE events SET question='Will the Democratic Party win the KY-03 House seat?' WHERE event_id='CM-EVT-9YCP3VGJR2';
UPDATE events SET question='Will the Democratic Party win the MA-02 House seat?' WHERE event_id='CM-EVT-7RNJ53L5L5';
UPDATE events SET question='Will the Democratic Party win the MA-04 House seat?' WHERE event_id='CM-EVT-622LC3YW64';
UPDATE events SET question='Will the Republican Party win the MS-01 House seat?' WHERE event_id='CM-EVT-PBSC8L0ZJ8';
UPDATE events SET question='Will the Democratic Party win the NC-14 House seat?' WHERE event_id='CM-EVT-QM85F2D2V9';
UPDATE events SET question='Will the Republican Party win the PA-16 House seat?' WHERE event_id='CM-EVT-G724FB9F24';
UPDATE events SET question='Will the Democratic Party win the TN-05 House seat?' WHERE event_id='CM-EVT-7NVN1N3X72';
UPDATE events SET question='Will the Republican Party win the TX-17 House seat?' WHERE event_id='CM-EVT-XPR3HN1ZW8';
UPDATE events SET question='Will the Republican Party win the TX-38 House seat?' WHERE event_id='CM-EVT-KJV4W96X81';
UPDATE events SET question='Will the Republican Party win the WV-01 House seat?' WHERE event_id='CM-EVT-C9K65NDY76';
UPDATE events SET question='Will the Republican Party win the WY-AL House seat?' WHERE event_id='CM-EVT-1RJ8686DQ2';
UPDATE events SET question='Will the next model released by xAI debut at a score of at least 1440?' WHERE event_id='CM-EVT-0P537T26J5';
