// Turns the enriched universe bundle into D1 seed SQL.
// Emits api/seed/schema.sql (DDL, idempotent) and api/seed/seed.sql (batched INSERTs).
// Also prints chosen demo slugs (the no-auth public events for Option-3 auth).
//
//   node api/scripts/export-d1.mjs [path-to-bundle]
//
// Default bundle: web/data/universe-enriched-full.json
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const REPO = resolve(__dirname, '..', '..');
const BUNDLE = process.argv[2] ?? resolve(REPO, 'web', 'data', 'universe-enriched-linked.json');
const SEED_DIR = resolve(__dirname, '..', 'seed');

const bundle = JSON.parse(readFileSync(BUNDLE, 'utf-8'));
const events = bundle.events ?? [];
const markets = bundle.markets ?? [];

// Eligibility screens (optional layer): per-market records + summary, written by
// screen_eligibility.py --write. Serialized into markets.eligibility_screens as the
// public spec shape [{regime, screen_version, status, reasons, bucket, screened_at}]
// (eligibility-screens-decision.md). Seed builds fine without the files.
let eligByMarket = {};
let eligVersion = '';
try {
  // Read both into temporaries and assign only if BOTH parse: the two files
  // are only valid as a pair (a populated map with an empty screen_version
  // would seed 6k versionless records and break result traceability).
  const byMarket = JSON.parse(readFileSync(resolve(REPO, 'web', 'data', 'eligibility-ciro-26-0076.json'), 'utf-8'));
  const version = JSON.parse(readFileSync(resolve(REPO, 'web', 'data', 'eligibility-ciro-26-0076-summary.json'), 'utf-8')).screen_version;
  if (!version) throw new Error('summary has no screen_version');
  eligByMarket = byMarket;
  eligVersion = version;
  console.error(`eligibility: ${Object.keys(eligByMarket).length} screened markets (screen ${eligVersion})`);
} catch (e) {
  eligByMarket = {};
  eligVersion = '';
  console.error(`eligibility: screen data unavailable or incomplete (${e?.message ?? e}) — eligibility_screens will be NULL`);
}
const eligScreens = (marketId) => {
  const r = eligByMarket[marketId];
  if (!r) return null;
  return [{
    regime: r.regime, screen_version: eligVersion, status: r.status,
    reasons: r.reasons ?? [], bucket: r.bucket ?? null, screened_at: r.screened_at,
  }];
};
console.error(`bundle: ${events.length} events / ${markets.length} markets (schema ${bundle._meta?.schema})`);

// ---- SQL value helpers -------------------------------------------------
const q = (v) => {
  if (v === null || v === undefined) return 'NULL';
  if (typeof v === 'number') return Number.isFinite(v) ? String(v) : 'NULL';
  if (typeof v === 'boolean') return v ? '1' : '0';
  return `'${String(v).replace(/'/g, "''")}'`;
};
const json = (v) => (v === null || v === undefined ? 'NULL' : `'${JSON.stringify(v).replace(/'/g, "''")}'`);

// ---- schema ------------------------------------------------------------
const schema = `-- ClearMarket D1 schema (generated by export-d1.mjs)
DROP TABLE IF EXISTS events;
DROP TABLE IF EXISTS markets;
DROP TABLE IF EXISTS catalyst_calendar;
DROP TABLE IF EXISTS resolution_log;
CREATE TABLE events (
  event_id TEXT PRIMARY KEY,
  slug TEXT UNIQUE NOT NULL,
  question TEXT NOT NULL,
  category TEXT NOT NULL,
  tags TEXT,
  primary_market_id TEXT,
  event_type TEXT,            -- 'BINARY' | 'LADDER' (multinomial strike ladder)
  ladder_distribution TEXT,   -- JSON {direction, implied_band, strikes[]} for LADDER events (patch_ladders.py)
  catalyst_types TEXT,        -- JSON array of catalyst-type pointers: ["cpi","fomc","earnings:NVDA"]
  catalyst_dates TEXT,        -- JSON array of BESPOKE per-event catalysts only (Exa/FDA); recurring derived at read-time
  venue TEXT,
  editorial_notes TEXT,
  bundle_type TEXT,            -- categorical|date_ladder|strike_ladder|augmented_negrisk|singleton
  resolution_reference TEXT,   -- generic subject-free event resolution ontology (OCC class-level rule)
  rcg_factors TEXT,            -- JSON: the 5 LLM factor ratings + "why" reasoning (audit trail)
  is_demo INTEGER NOT NULL DEFAULT 0,
  published INTEGER NOT NULL DEFAULT 1,
  created_at TEXT,
  updated_at TEXT
);
CREATE INDEX idx_events_category ON events(category);
CREATE INDEX idx_events_demo ON events(is_demo);

-- Shared catalyst calendar: type -> {label, source_url, dates[]}. The Worker joins
-- events.catalyst_types against this at read-time and windows by resolution date.
-- Refreshed monthly (recurring macro + demand-driven earnings); no per-event storage.
CREATE TABLE catalyst_calendar (
  type TEXT PRIMARY KEY,      -- 'cpi' | 'jobs' | 'gdp' | 'fomc' | 'earnings:<TICKER>'
  label TEXT NOT NULL,
  source_url TEXT NOT NULL,
  dates TEXT NOT NULL         -- JSON array of ISO dates
);

CREATE TABLE markets (
  market_id TEXT PRIMARY KEY,
  event_id TEXT NOT NULL,
  platform TEXT,
  platform_market_id TEXT,
  question_raw TEXT,
  description_raw TEXT,
  contract_type TEXT,
  settlement_currency TEXT,
  underlying_reference TEXT,
  group_item_title TEXT,       -- per-child subject (the OSI-symbol analog; composes underlying_reference)
  close_at TEXT,
  resolve_at TEXT,
  status TEXT,
  resolution_rules_raw TEXT,
  arbitration_model TEXT,
  resolution_proposer TEXT,
  resolution_source TEXT,
  source_citation TEXT,
  resolution_source_type TEXT,
  resolution_source_quality TEXT,
  source_commitment TEXT,
  source_commitment_subtype TEXT,
  source_of_record TEXT,       -- the committed authority the LLM identified (grade-only; display stays verbatim)
  resolution_source_list TEXT, -- JSON [{name,url,provenance}] — full venue-listed + prose-surfaced source set
  source_status TEXT,          -- stamped at enrich: platform_named | no_committed_source | no_source_stated
  source_mechanism TEXT,       -- single_authority | precedence | quorum
  source_hedge_text TEXT,
  resolution_clarity_grade TEXT,
  rcg_score INTEGER,
  rcg_caps TEXT,
  rcg_applied_factors INTEGER,
  rcg TEXT,                    -- JSON audit: per-factor {rating,engine,weight,points} + caps + commitment
  last_price REAL,
  volume_24h_usd REAL,
  volume_total_usd REAL,
  last_updated_at TEXT,      -- ISO; stamped by the hourly marks cron on every price write (NULL until first refresh)
  reconciled_at TEXT,        -- ISO; stamped by the daily reconcileStatus cron when it confirms a market's status vs the venue
  settlement_style TEXT,
  direction TEXT,
  threshold REAL,
  question_id TEXT,
  also_on TEXT,              -- JSON [{venue, market_id, price}] of the same question on other venues; NULL if unique
  tags TEXT,
  eligibility_screens TEXT   -- JSON [{regime, screen_version, status, reasons, bucket, screened_at}]; rule-set fit, NOT market quality
);
CREATE INDEX idx_markets_event ON markets(event_id);
CREATE INDEX idx_markets_grade ON markets(resolution_clarity_grade);
CREATE INDEX idx_markets_platform ON markets(platform);
CREATE INDEX idx_markets_question ON markets(question_id);
CREATE INDEX idx_markets_platform_mkt ON markets(platform_market_id);

-- Auth (Option 3): free-key signup + per-day rate limiting.
CREATE TABLE IF NOT EXISTS api_keys (
  key TEXT PRIMARY KEY,
  email TEXT NOT NULL,
  created_at TEXT NOT NULL,
  daily_limit INTEGER NOT NULL DEFAULT 1000,
  revoked INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS usage (
  key TEXT NOT NULL,
  day TEXT NOT NULL,
  count INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (key, day)
);
CREATE TABLE IF NOT EXISTS spot (
  coin TEXT PRIMARY KEY,
  price_usd REAL,
  as_of TEXT
);

-- Per-call audit log: one row per data request to the REST API or MCP. Records WHAT was
-- queried (which endpoint/tool + the key argument), WHO (api key or ip), and from WHERE.
-- Operational table — IF NOT EXISTS so it persists across reseeds (like api_keys/usage).
CREATE TABLE IF NOT EXISTS call_log (
  ts TEXT NOT NULL,           -- ISO timestamp of the call
  surface TEXT NOT NULL,      -- 'rest' | 'mcp'
  action TEXT NOT NULL,       -- endpoint or MCP tool name (e.g. 'get_event', 'list_events')
  target TEXT,                -- the key argument: slug / market_id / JSON of filters
  requester TEXT,             -- 'key:<key>' if authenticated, else 'ip:<addr>'
  country TEXT,               -- Cloudflare-resolved country of the caller
  user_agent TEXT             -- request UA — crawlers self-identify (GPTBot, ClaudeBot, …)
);
CREATE INDEX IF NOT EXISTS idx_call_log_ts ON call_log(ts);

-- End-of-day price/volume history (one row per market per day). Hourly cron keeps
-- markets.last_price fresh in place; this table is the daily time-series captured at the
-- EOD cron hour, so wires can report multi-day moves + volume-spike baselines. Scoped to
-- the ~2,700 linked+primary markets the marks cron actually refreshes (others stay stale).
CREATE TABLE IF NOT EXISTS marks_daily (
  market_id TEXT NOT NULL,
  day TEXT NOT NULL,
  last_price REAL,
  volume_24h_usd REAL,
  volume_total_usd REAL,
  captured_at TEXT,
  PRIMARY KEY (market_id, day)
);
CREATE INDEX IF NOT EXISTS idx_marks_daily_mkt ON marks_daily(market_id);

-- Resolution log: append-only resolved-market history (built by build_resolution_log.py from the
-- price+date snapshot). Reseeded from the bundle each export, so DROP+CREATE like events/markets.
CREATE TABLE resolution_log (
  market_id TEXT NOT NULL,
  event_id TEXT NOT NULL,
  platform TEXT,
  event_type TEXT,            -- 'resolved' | 'status_change'
  occurred_at TEXT,           -- when it settled (venue settlement time; deadline only as fallback)
  occurred_basis TEXT,        -- 'venue_settlement' | 'deadline' (which of the two occurred_at holds)
  recorded_at TEXT,           -- pull date that first observed it
  from_value TEXT,            -- prior state (e.g. 'open'); NULL for legacy rows
  to_value TEXT,              -- 'YES' | 'NO' | 'PENDING' (resolved) | 'closed' (status_change)
  final_price REAL,
  source TEXT,
  source_ref TEXT,
  actor TEXT,
  PRIMARY KEY (market_id, occurred_at)
);
CREATE INDEX idx_resolution_log_event ON resolution_log(event_id);
`;

// ---- choose demo events (top A-grade by primary-market volume) ---------
const marketById = new Map(markets.map((m) => [m.market_id, m]));
const demoSlugs = events
  .filter((e) => e.primary_market_id)
  .map((e) => ({ e, pm: marketById.get(e.primary_market_id) }))
  .filter(({ pm }) => pm && pm.resolution_clarity_grade === 'A')
  .sort((a, b) => (b.pm.volume_total_usd ?? 0) - (a.pm.volume_total_usd ?? 0))
  .slice(0, 3)
  .map(({ e }) => e.slug);
const demoSet = new Set(demoSlugs);

// ---- seed --------------------------------------------------------------
// D1 caps a single SQL statement at 100KB. Batch by byte-size, not row-count,
// so long resolution-rules text can't blow the cap. Target ~60KB/statement.
const MAX_BYTES = 60000;
function chunkBySize(rows, prefix) {
  const stmts = [];
  let cur = [];
  let len = prefix.length + 1;
  for (const r of rows) {
    if (cur.length && len + r.length + 2 > MAX_BYTES) {
      stmts.push(`${prefix}\n${cur.join(',\n')};`);
      cur = []; len = prefix.length + 1;
    }
    cur.push(r); len += r.length + 2;
  }
  if (cur.length) stmts.push(`${prefix}\n${cur.join(',\n')};`);
  return stmts;
}

const eRows = events.map((e) => `(${[
  q(e.event_id), q(e.slug), q(e.question), q(e.category), json(e.tags),
  q(e.primary_market_id), q(e.event_type ?? 'BINARY'), json(e.ladder_distribution ?? null),
  json(e.catalyst_types ?? []), json(e.catalyst_dates ?? []), q(e.venue), q(e.editorial_notes),
  q(e.bundle_type), q(e.resolution_reference), json(e.rcg_factors ?? null),
  demoSet.has(e.slug) ? '1' : '0', e.published === false ? '0' : '1',
  q(e.created_at), q(e.updated_at),
].join(',')})`);

// ---- catalyst calendar seed (type-keyed; read from data/catalyst-calendar.json) ----
const CAL_PATH = resolve(REPO, 'data', 'catalyst-calendar.json');
let calRows = [];
try {
  const cal = JSON.parse(readFileSync(CAL_PATH, 'utf-8'));
  const types = cal.types ?? {};
  calRows = Object.entries(types).map(([type, c]) =>
    `(${[q(type), q(c.label), q(c.source_url), json(c.dates ?? [])].join(',')})`);
  console.error(`catalyst calendar: ${calRows.length} types`);
} catch (err) {
  console.error(`WARN: no catalyst-calendar.json (${err.message}) — calendar table will be empty`);
}

const mRows = markets.map((m) => `(${[
  q(m.market_id), q(m.event_id), q(m.platform), q(m.platform_market_id),
  q(m.question_raw), q(m.description_raw), q(m.contract_type), q(m.settlement_currency),
  q(m.underlying_reference), q(m.group_item_title), q(m.close_at), q(m.resolve_at), q(m.status),
  q(m.resolution_rules_raw), q(m.arbitration_model), q(m.resolution_proposer),
  q(m.resolution_source), q(m.source_citation), q(m.resolution_source_type),
  q(m.resolution_source_quality), q(m.source_commitment), q(m.source_commitment_subtype),
  q(m.source_of_record), json(m.resolution_source_list ?? null), q(m.source_status),
  q(m.source_mechanism), q(m.source_hedge_text), q(m.resolution_clarity_grade), q(m.rcg_score),
  json(m.rcg_caps), q(m.rcg_applied_factors), json(m.rcg ?? null), q(m.last_price), q(m.volume_24h_usd), q(m.volume_total_usd),
  q(m.settlement_style), q(m.direction), q(m.threshold), q(m.question_id), json(m.also_on ?? null), json(m.tags), json(eligScreens(m.market_id)),
].join(',')})`);

// ---- resolution log seed (read from web/data/resolution-log.json) ----
const RESLOG_PATH = resolve(REPO, 'web', 'data', 'resolution-log.json');
let rlRows = [];
try {
  const rlog = JSON.parse(readFileSync(RESLOG_PATH, 'utf-8'));
  rlRows = (Array.isArray(rlog) ? rlog : []).map((r) => `(${[
    q(r.market_id), q(r.event_id), q(r.platform), q(r.event_type),
    q(r.occurred_at), q(r.occurred_basis ?? null), q(r.recorded_at), q(r.from_value ?? null), q(r.to_value), q(r.final_price),
    q(r.source), q(r.source_ref), q(r.actor),
  ].join(',')})`);
  console.error(`resolution log: ${rlRows.length} resolved markets`);
} catch (err) {
  console.error(`WARN: no resolution-log.json (${err.message}) — resolution_log table will be empty`);
}

const batches = [
  ...chunkBySize(eRows, 'INSERT INTO events (event_id,slug,question,category,tags,primary_market_id,event_type,ladder_distribution,catalyst_types,catalyst_dates,venue,editorial_notes,bundle_type,resolution_reference,rcg_factors,is_demo,published,created_at,updated_at) VALUES'),
  ...chunkBySize(mRows, 'INSERT INTO markets (market_id,event_id,platform,platform_market_id,question_raw,description_raw,contract_type,settlement_currency,underlying_reference,group_item_title,close_at,resolve_at,status,resolution_rules_raw,arbitration_model,resolution_proposer,resolution_source,source_citation,resolution_source_type,resolution_source_quality,source_commitment,source_commitment_subtype,source_of_record,resolution_source_list,source_status,source_mechanism,source_hedge_text,resolution_clarity_grade,rcg_score,rcg_caps,rcg_applied_factors,rcg,last_price,volume_24h_usd,volume_total_usd,settlement_style,direction,threshold,question_id,also_on,tags,eligibility_screens) VALUES'),
  ...(calRows.length ? chunkBySize(calRows, 'INSERT INTO catalyst_calendar (type,label,source_url,dates) VALUES') : []),
  ...(rlRows.length ? chunkBySize(rlRows, 'INSERT INTO resolution_log (market_id,event_id,platform,event_type,occurred_at,occurred_basis,recorded_at,from_value,to_value,final_price,source,source_ref,actor) VALUES') : []),
];

writeFileSync(resolve(SEED_DIR, 'schema.sql'), schema);
writeFileSync(resolve(SEED_DIR, 'seed.sql'), batches.join('\n'));

// meta sidecar the Worker can import for /health
writeFileSync(resolve(SEED_DIR, 'meta.json'), JSON.stringify({
  generated_at: bundle._meta?.generated_at ?? new Date().toISOString(),
  schema: bundle._meta?.schema ?? 'v0.2.0',
  event_count: events.length,
  market_count: markets.length,
  demo_slugs: demoSlugs,
}, null, 2));

console.error(`wrote schema.sql, seed.sql (${batches.length} batches), meta.json`);
console.error(`demo slugs: ${demoSlugs.join(' | ')}`);
