/**
 * Renders spike results into `findings.md` — a note formatted so it can be
 * appended to the market-data acquisition notes nearly verbatim. Keys are
 * never printed; only presence/absence.
 */

import type { CheckStatus, ProviderId, RunResult } from "./harness.ts"

export interface FindingsMeta {
  readonly runDate: string
  readonly fdKeyPresent: boolean
  readonly eodhdRealKey: boolean
}

const BADGE: Record<CheckStatus, string> = {
  pass: "PASS",
  warn: "WARN",
  fail: "FAIL",
  skipped: "SKIP",
}

const PROVIDER_TITLE: Record<ProviderId, string> = {
  "financial-datasets": "Financial Datasets (US equities)",
  eodhd: "EODHD (Oslo Børs, international, FX)",
}

function tally(results: readonly RunResult[]): Record<CheckStatus, number> {
  const counts: Record<CheckStatus, number> = { pass: 0, warn: 0, fail: 0, skipped: 0 }
  for (const r of results) counts[r.status] += 1
  return counts
}

function renderCheck(result: RunResult): string {
  const lines = [`### [${BADGE[result.status]}] \`${result.check.id}\` — ${result.check.title}`, "", result.detail]
  if (result.evidence !== undefined) {
    lines.push("", "```json", JSON.stringify(result.evidence, null, 2), "```")
  }
  return lines.join("\n")
}

function renderProvider(provider: ProviderId, results: readonly RunResult[]): string {
  const own = results.filter((r) => r.check.provider === provider)
  if (own.length === 0) return ""
  const counts = tally(own)
  const header =
    `## ${PROVIDER_TITLE[provider]}\n\n` +
    `_${counts.pass} pass · ${counts.warn} warn · ${counts.fail} fail · ${counts.skipped} skipped_`
  return [header, "", own.map(renderCheck).join("\n\n")].join("\n")
}

const INTERPRETATION = `## Interpretation (human judgment required)

These verdicts turn the raw checks above into plan decisions. Fill the TODOs
from the evidence once a run with the relevant keys is available.

- **Estimate-vintage verdict (surprise vs. momentum).** TODO — from
  \`fd-earnings-estimates\` (and \`eodhd-oslo-earnings\`): if no estimate
  as-of/vintage field exists on either provider, the earnings *surprise*
  strategy is reframed as **earnings momentum** (reported-actual vs.
  same-quarter-last-year), tagged and backtested as a distinct signal — never
  sold as PEAD. Decide: keep surprise anywhere, or momentum-only?

- **Adjustment-semantics verdict.** TODO — from \`fd-prices-adjustment\` and
  \`eodhd-adjusted-close\`: state, per provider, exactly which field feeds
  \`close\` and which feeds \`adjClose\`, and whether the mapper must derive a
  split factor itself or the vendor already back-adjusts. This is the auditable
  price-adjustment convention the backtest depends on.

- **Oslo filing_date verdict (the linchpin).** TODO — from
  \`eodhd-oslo-filing-date\`: if filing_date is populated for (nearly) all
  recent Oslo quarters, PIT knownAt is derivable directly and Oslo fundamentals
  are first-class. If not, knownAt falls back to period-date coerced to
  exchange EOD, tagged lower-confidence, and the gap is documented as a known
  limitation for XOSL.

- **Retention / licensing.** TODO — confirm the recorded cassettes may be kept
  privately (gitignored, never redistributed) and that only derived output is
  exposed to hosted users, per plan 003's two supported modes.`

export function renderFindings(results: readonly RunResult[], meta: FindingsMeta): string {
  const counts = tally(results)
  const providers: ProviderId[] = ["financial-datasets", "eodhd"]
  const eodhdTier = meta.eodhdRealKey ? "real key" : "demo tier (public `demo` token)"

  const head = [
    "# Plan 003 — Phase 0 provider spike findings",
    "",
    `**Run date:** ${meta.runDate}`,
    `**Keys present:** Financial Datasets: ${meta.fdKeyPresent ? "yes" : "no"} · EODHD: ${eodhdTier}`,
    `**Results:** ${results.length} checks — ${counts.pass} pass, ${counts.warn} warn, ${counts.fail} fail, ${counts.skipped} skipped`,
    "",
    "> Generated by `pnpm --filter @workspace/engine spike`. Raw provider payloads",
    "> are saved under `spike/output/cassettes/` (gitignored — never committed,",
    "> per plan 003's private-tier licensing rule). Skipped checks need a key that",
    "> was not present on this run.",
  ].join("\n")

  const body = providers
    .map((p) => renderProvider(p, results))
    .filter((s) => s.length > 0)
    .join("\n\n")

  return [head, "", body, "", INTERPRETATION, ""].join("\n")
}
