"""add event_relationships table

Revision ID: 1d7d8eb38a2e
Revises: f8e311a02850
Create Date: 2026-04-16 23:38:06.459972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d7d8eb38a2e'
down_revision: Union[str, Sequence[str], None] = 'f8e311a02850'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_relationships',
    sa.Column('relationship_id', sa.String(), nullable=False),
    sa.Column('from_event_id', sa.String(), nullable=False),
    sa.Column('to_event_id', sa.String(), nullable=False),
    sa.Column('relationship_type', sa.String(length=40), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('relationship_id')
    )
    op.create_index(op.f('ix_event_relationships_from_event_id'), 'event_relationships', ['from_event_id'], unique=False)
    op.create_index(op.f('ix_event_relationships_to_event_id'), 'event_relationships', ['to_event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_relationships_to_event_id'), table_name='event_relationships')
    op.drop_index(op.f('ix_event_relationships_from_event_id'), table_name='event_relationships')
    op.drop_table('event_relationships')
    # ### end Alembic commands ###
