"""
Company name → ticker symbol mapping for extracting tickers from article text.

Covers major US-listed companies by market cap and trading volume.
Names are lowercase for case-insensitive matching.
"""

# Map of company name fragments (lowercase) → ticker symbol
# Use the shortest unambiguous form of the company name
COMPANY_TO_TICKER: dict[str, str] = {
    # Mega-cap tech
    "apple": "AAPL",
    "microsoft": "MSFT",
    "alphabet": "GOOGL",
    "google": "GOOGL",
    "amazon": "AMZN",
    "nvidia": "NVDA",
    "meta platforms": "META",
    "tesla": "TSLA",
    "broadcom": "AVGO",
    "taiwan semiconductor": "TSM",
    "tsmc": "TSM",
    # Large-cap tech
    "adobe": "ADBE",
    "salesforce": "CRM",
    "netflix": "NFLX",
    "amd": "AMD",
    "advanced micro devices": "AMD",
    "intel": "INTC",
    "qualcomm": "QCOM",
    "cisco": "CSCO",
    "oracle": "ORCL",
    "ibm": "IBM",
    "servicenow": "NOW",
    "intuit": "INTU",
    "uber": "UBER",
    "airbnb": "ABNB",
    "palantir": "PLTR",
    "snowflake": "SNOW",
    "crowdstrike": "CRWD",
    "palo alto networks": "PANW",
    "datadog": "DDOG",
    "shopify": "SHOP",
    "spotify": "SPOT",
    "snap inc": "SNAP",
    "snapchat": "SNAP",
    "pinterest": "PINS",
    "twilio": "TWLO",
    "roku": "ROKU",
    "coinbase": "COIN",
    "robinhood": "HOOD",
    "block inc": "SQ",
    "square": "SQ",
    "paypal": "PYPL",
    "micron": "MU",
    "arm holdings": "ARM",
    "asml": "ASML",
    "marvell": "MRVL",
    "applied materials": "AMAT",
    "lam research": "LRCX",
    "synopsys": "SNPS",
    "cadence design": "CDNS",
    "dell technologies": "DELL",
    "hewlett packard": "HPE",
    "hp inc": "HPQ",
    # Finance
    "jpmorgan": "JPM",
    "jp morgan": "JPM",
    "bank of america": "BAC",
    "wells fargo": "WFC",
    "goldman sachs": "GS",
    "morgan stanley": "MS",
    "citigroup": "C",
    "charles schwab": "SCHW",
    "blackrock": "BLK",
    "blackstone": "BX",
    "kkr": "KKR",
    "apollo global": "APO",
    "american express": "AXP",
    "visa inc": "V",
    "mastercard": "MA",
    "berkshire hathaway": "BRK.B",
    # Healthcare / Pharma
    "unitedhealth": "UNH",
    "johnson & johnson": "JNJ",
    "eli lilly": "LLY",
    "novo nordisk": "NVO",
    "abbvie": "ABBV",
    "merck": "MRK",
    "pfizer": "PFE",
    "amgen": "AMGN",
    "gilead": "GILD",
    "moderna": "MRNA",
    "regeneron": "REGN",
    "vertex pharma": "VRTX",
    "biogen": "BIIB",
    "bristol-myers": "BMY",
    "astrazeneca": "AZN",
    "novartis": "NVS",
    "roche": "RHHBY",
    "thermo fisher": "TMO",
    "danaher": "DHR",
    "abbott labs": "ABT",
    "medtronic": "MDT",
    "intuitive surgical": "ISRG",
    "stryker": "SYK",
    "edwards lifesciences": "EW",
    "humana": "HUM",
    "cigna": "CI",
    "cvs health": "CVS",
    # Energy
    "exxon": "XOM",
    "exxonmobil": "XOM",
    "chevron": "CVX",
    "conocophillips": "COP",
    "schlumberger": "SLB",
    "marathon petroleum": "MPC",
    "valero": "VLO",
    "phillips 66": "PSX",
    "pioneer natural": "PXD",
    "occidental": "OXY",
    "devon energy": "DVN",
    "baker hughes": "BKR",
    "halliburton": "HAL",
    "enbridge": "ENB",
    # Consumer / Retail
    "walmart": "WMT",
    "costco": "COST",
    "home depot": "HD",
    "lowe's": "LOW",
    "target corp": "TGT",
    "procter & gamble": "PG",
    "coca-cola": "KO",
    "pepsi": "PEP",
    "pepsico": "PEP",
    "mcdonald's": "MCD",
    "starbucks": "SBUX",
    "nike": "NKE",
    "disney": "DIS",
    "walt disney": "DIS",
    "comcast": "CMCSA",
    "t-mobile": "TMUS",
    "verizon": "VZ",
    "at&t": "T",
    # Industrial / Defense
    "boeing": "BA",
    "lockheed martin": "LMT",
    "raytheon": "RTX",
    "northrop grumman": "NOC",
    "general dynamics": "GD",
    "general electric": "GE",
    "honeywell": "HON",
    "caterpillar": "CAT",
    "deere": "DE",
    "john deere": "DE",
    "3m company": "MMM",
    "union pacific": "UNP",
    "ups": "UPS",
    "fedex": "FDX",
    # Auto
    "ford motor": "F",
    "general motors": "GM",
    "rivian": "RIVN",
    "lucid": "LCID",
    "nio": "NIO",
    "toyota": "TM",
    # Real estate / REITs
    "prologis": "PLD",
    "american tower": "AMT",
    "crown castle": "CCI",
    "equinix": "EQIX",
    "digital realty": "DLR",
    # Other notable
    "accenture": "ACN",
    "automatic data": "ADP",
    "booking holdings": "BKNG",
    "chipotle": "CMG",
    "constellation energy": "CEG",
    "duke energy": "DUK",
    "nexterra": "NEE",
    "nextera energy": "NEE",
    "southern company": "SO",
    "dominion energy": "D",
    "linde": "LIN",
    "air products": "APD",
    "freeport-mcmoran": "FCX",
    "newmont": "NEM",
    "mosaic": "MOS",
    "u.s. steel": "X",
    "us steel": "X",
    "nucor": "NUE",
    "cleveland-cliffs": "CLF",
    # Chinese ADRs
    "alibaba": "BABA",
    "baidu": "BIDU",
    "jd.com": "JD",
    "pinduoduo": "PDD",
    "byd": "BYDDY",
    "li auto": "LI",
    "xpeng": "XPEV",
    # Crypto-adjacent
    "microstrategy": "MSTR",
    "marathon digital": "MARA",
    "riot platforms": "RIOT",
}
